# Puxado diretamente da URL da imagem image_9acbfc.png
sonar.organization=guard-ia-grupo5
sonar.projectKey=guard-ia-grupo5_guard-ia
sonar.projectName=Guard.IA

# Pastas que o Sonar deve ler
sonar.sources=grupo5-guard.ia/src, grupo5-guard.ia-backend
sonar.sourceEncoding=UTF-8

# Pastas a serem ignoradas
sonar.exclusions=**/node_modules/**, **/.next/**, **/.venv/**, **/dist/**, **/*.test.js